export enum LogActions {
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  CREATE_STUDENT = 'CREATE_STUDENT',
  UPDATE_STUDENT = 'UPDATE_STUDENT',
  DELETE_STUDENT = 'DELETE_STUDENT',
  CREATE_SESSION = 'CREATE_SESSION',
  START_SESSION = 'START_SESSION',
  COMPLETE_SESSION = 'COMPLETE_SESSION',
  UPDATE_NOTES = 'UPDATE_NOTES',
  GENERATE_AI_PLAN = 'GENERATE_AI_PLAN',
  GENERATE_AI_DEBRIEF = 'GENERATE_AI_DEBRIEF',
  GENERATE_PROGRESS = 'GENERATE_PROGRESS',
}

export enum LogEntityType {
  USER = 'USER',
  STUDENT = 'STUDENT',
  SESSION = 'SESSION',
}

export enum LogStatus {
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}
